language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# no dependencies (coveralls only for coverage and ipython only for testing optional IPython extension)
install: pip install coveralls ipython

script: nosetests --with-doctest --with-coverage --cover-package=param

after_success: coveralls
